name: Sync to Google Sheets

on:
  schedule:
    - cron: "0 * * * *"  # 毎時0分に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのコードを取得
        uses: actions/checkout@v3

      - name: Node.js をセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 作業ディレクトリを確認
        run: pwd && ls -la

      - name: パッケージをインストール
        working-directory: ${{ github.workspace }}
        run: npm install

      - name: Google スプレッドシートにデータを同期
        run: node server.js
